### ISSUE TITLE
Unnecessary open port in docker-compose

### ISSUE THREAD

**Issue by chipironcin** [bitnami/bitnami-docker-java-play#48]
**Description**
Probably unnecessary '8888' open port at every docker-compose file in this repo.

**Steps to reproduce the issue:**
`docker-compose up`

**Describe the results you received:**
It opens the `8888` port.

**Describe the results you expected:**
No open nor binded `8888` port
Dockerfile does not export it so I suppose it is not needed.

**Comment by dbarranco** [comment]
As described in [their documentation](https://www.playframework.com/documentation/2.6.x/ProductionConfiguration#specifying-the-http-server-address-and-port-using-system-properties) the only default port is `9000`. So the `8888` port is unnecessary here.

I hope this information is useful for you. 

Thank you and best regards,
David Barranco.

****
Was my answer helpful? Click on :heart:
